spring:
  profiles:
    active: -dev
---
server:
  port: 8203
spring:
  profiles: dev
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka